- name: web server
  hosts: web_server
  become: yes
  tasks:
    - name: Install package
      yum:
        name:
          - yum-utils
          - git
          - vim
          - firewalld
        state: present

    # ---
    # START firewalld configuration
    - name: Config Firewalld allow 'http' protocol
      firewalld:
        service: http
        permanent: yes
        state: enabled
      notify: Restart Firewalld

    - name: Config Firewalld allow 'ssh' protocol
      firewalld:
        service: ssh
        permanent: yes
        state: enabled
      notify: Restart Firewalld

    - name: Config Firewalld allow 'https' protocol
      firewalld:
        service: https
        permanent: yes
        state: enabled
      notify: Restart Firewalld

    - name: Config Firewalld allow 'mysql' protocol
      firewalld:
        service: mysql
        permanent: yes
        state: enabled
      notify: Restart Firewalld

    - name: Config Firewalld allow '8080' tcp
      firewalld:
        port: "{{ app_port }}/tcp"
        permanent: yes
        state: enabled
      notify: Restart Firewalld

    - name: Config Firewalld allow '9000' tcp / portainer
      firewalld:
        port: "9000/tcp"
        permanent: yes
        state: enabled
      notify: Restart Firewalld
    # END firewalld configuration

    # ---
    # Start docker configuration
    - name: Remove docker if installed from CentOS repo
      yum:
        name:
          - docker
          - docker-client
          - docker-client-latest
          - docker-common
          - docker-latest
          - docker-latest-logrotate
          - docker-logrotate
          - docker-engine
        state: absent

    - name: Add Docker repo
      get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docer-ce.repo

    - name: Enable Docker Edge repo
      ini_file:
        dest: /etc/yum.repos.d/docer-ce.repo
        section: 'docker-ce-edge'
        option: enabled
        value: 0

    - name: Enable Docker Test repo
      ini_file:
        dest: /etc/yum.repos.d/docer-ce.repo
        section: 'docker-ce-test'
        option: enabled
        value: 0

    - name: Install package
      yum:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: adding existing user '{{ ansible_user }}' to group docker
      user:
        name: '{{ ansible_user }}'
        groups: docker
        append: yes
    # End docker configuration

  # ---
  # handlers - handler will be triggered when config change
  handlers:
  - name: Restart Firewalld
    service:
      name: firewalld
      state: restarted

  - name: Restart docker
    service:
      name: docker
      state: restarted